Test a1 f1 (#70)
* Commit 1

* updated test

* removed old packer

* updated the packer-ci

* modified the yml file

* updating the yml file

* create ci merge

* updated packer-ci-merge

* updated merge file

* updated yml

* updated packer.hcl

* updated bash file

* updated yml

* updated packer hcl

* updated hcl

* Update aws-debian.pkr.hcl

* updated packer file

* updated packer

* updated packer

* updated hcl with fmt

* updated packer file

* updated packer

* updated hcl

* updated hcl

* updated bash file

* Updated the packer file

* updated bash

* updated bash

* updated packer.hcl

* updated database sh file

* Update aws-debian.pkr.hcl

* updated packer hcl

* Updated packer hcl

* Updated hcl and ci merge

* Updated ci merege

* Updated files

* Updated packer

* formated packer

* updated local host

* updated bash

* updated bash and hcl file

* formated hcl

* updated api and basic auth

* upadated code

* updated env

* updated bash

* updated bash

* updated hcl file

* Updated some files, added webasp.service file

* updated packer file

* updated packer file

* updated bash

* Updated env file

* Updated DB.js

* updated the bash file

* Updated service fille

* updated webapp.service file

* Modified server.js

* updated bash file

* updated packer file

* updated bash

* updated  bash

* updated bash

* updated bash

* updated bash

* updated webapp.service

* Update aws-debian.pkr.hcl

* updated packer

* updated bash

* updated webapp.service

* Updated webapp

* Updated code

* Updated packge.json

* Updated the Code

* Update the Packer file

* Updated yaml file

* Updated the yaml

* Updated Code in Yaml file

* Update packer-ci-merge.yml

* Update app.js

* updated the webapp

* Updated Yaml

* Updated YML

* Updated the packer file

* Updated packer

* Updated yml

* upadted

* updatd code

* Updated chnags

* Updated code

* Update packer-ci-LT.yml

* Updated code

diff --git a/.github/workflows/packer-ci-LT.yml b/.github/workflows/packer-ci-LT.yml
--- a/.github/workflows/packer-ci-LT.yml
+++ b/.github/workflows/packer-ci-LT.yml
@@ -52,8 +52,6 @@ jobs:
           echo "Using Launch Template ID: $LAUNCH_TEMPLATE_ID" # For debugging
           echo "Using Launch Template ID: $LATEST_VERSION" # For debugging
           aws ec2 create-launch-template-version --launch-template-id "$LAUNCH_TEMPLATE_ID" --source-version "$LATEST_VERSION" --launch-template-data "{\"ImageId\":\"$AMI_ID\"}"
-
-
       # - name: Retrieve latest Launch Template version
       #   run: |
       #     LAUNCH_TEMPLATE_NAME="app-launch-template"
@@ -71,36 +69,37 @@ jobs:
 # hahah
 
       
-      - name: Update ASG to use the latest Launch Template version
-        run: |
-          ASG_NAME="app-auto-scaling-group"
-          LAUNCH_TEMPLATE_NAME="${{ env.LAUNCH_TEMPLATE_NAME }}"
-          LATEST_VERSION=${{env.latest_version_new}}
-          echo "Using Launch Template ID: $LATEST_VERSION" # For debugging
-          aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$ASG_NAME" --launch-template "LaunchTemplateName=$LAUNCH_TEMPLATE_NAME,Version=$LATEST_VERSION"
+      # - name: Update ASG to use the latest Launch Template version
+      #   run: |
+      #     ASG_NAME="app-auto-scaling-group"
+      #     LAUNCH_TEMPLATE_NAME="${{ env.LAUNCH_TEMPLATE_NAME }}"
+      #     LATEST_VERSION=${{env.latest_version_new}}
+      #     echo "Using Launch Template ID: $LATEST_VERSION" # For debugging
+      #     aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$ASG_NAME" --launch-template "LaunchTemplateName=$LAUNCH_TEMPLATE_NAME,Version=8"
 
       
-      - name: Start Instance Refresh
-        run: |
-          INSTANCE_REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name "app-auto-scaling-group" --strategy "Rolling" --query 'InstanceRefreshId' --output text)
+      # - name: Start Instance Refresh
+      #   run: |
+      #     INSTANCE_REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name "app-auto-scaling-group" --strategy "Rolling" --query 'InstanceRefreshId' --output text)
 
-          echo "Instance Refresh ID: $INSTANCE_REFRESH_ID"
-          echo "INSTANCE_REFRESH_ID=$INSTANCE_REFRESH_ID" >> $GITHUB_ENV
+      #     echo "Instance Refresh ID: $INSTANCE_REFRESH_ID"
+      #     echo "INSTANCE_REFRESH_ID=$INSTANCE_REFRESH_ID" >> $GITHUB_ENV
 
-      - name: Wait for Instance Refresh Completion
-        run: |
-          while true; do
-              STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name "app-auto-scaling-group" --instance-refresh-ids "${{ env.INSTANCE_REFRESH_ID }}" --query 'InstanceRefreshes[0].Status' --output text)
+      # - name: Wait for Instance Refresh Completion
+      #   run: |
+      #     while true; do
+      #         STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name "app-auto-scaling-group" --instance-refresh-ids "${{ env.INSTANCE_REFRESH_ID }}" --query 'InstanceRefreshes[0].Status' --output text)
 
-              if [ "$STATUS" = "Successful" ]; then
-                  echo "Instance refresh completed successfully"
-                  break
-              elif [ "$STATUS" = "Failed" ]; then
-                  echo "Instance refresh failed"
-                  exit 1
-              else
-                  echo "Waiting for instance refresh... Current status: $STATUS"
-                  sleep 60
-              fi
-          done
+      #         if [ "$STATUS" = "Successful" ]; then
+      #             echo "Instance refresh completed successfully"
+      #             break
+      #         elif [ "$STATUS" = "Failed" ]; then
+      #             echo "Instance refresh failed"
+      #             exit 1
+      #         else
+      #             echo "Waiting for instance refresh... Current status: $STATUS"
+      #             sleep 60
+      #         fi
+      #     done
           
+
